document.writeln("<meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("<script src=\'https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.3/js/bootstrap.min.js\'></script>");
document.writeln("<link href=\'https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.3/css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css\' rel=\'stylesheet\'>");
document.writeln("    <script src=\'/js/dark.js\'></script>");
document.writeln("    <link rel=\'manifest\' href=\'/manifest.json\' />");
document.writeln("<!-- 手机适配标识 -->");
document.writeln("<meta name=\'apple-mobile-web-app-capable\' content=\'yes\'>");
document.writeln("<meta name=\'mobile-web-app-capable\' content=\'yes\'>");
document.writeln("<!-- 配置主题颜色 -->");
document.writeln("<meta name=\'theme-color\' content=\'#ffffff\'>");
document.writeln("<!-- 配置添加到主屏幕时的标题 -->");
document.writeln("<meta name=\'apple-mobile-web-app-title\' content=\'猪圈\'>");
document.writeln("<!-- 配置添加到主屏幕时的icon -->");
document.writeln("<link rel=\'apple-touch-icon-precomposed\' sizes=\'512x512\' href=\'/favicon.ico\'>");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'512x512\' href=\'/favicon.ico\'>");
document.writeln("    <!-- 灯箱脚本 -->");
document.writeln("    <script src=\'/js/view-image.min (1).js\'></script>");
document.writeln("    <script>");
document.writeln("        window.ViewImage && ViewImage.init(\'.img\');");
document.writeln("    </script>");
document.writeln("    <link rel=\'stylesheet\' href=\'/index.css\'>");