document.writeln("<!-- 导航栏 -->");
document.writeln("    <nav class=\'navbar navbar-expand-lg navbar-light sticky-top shadow-sm\'>");
document.writeln("        <div class=\'container-fluid d-flex\'><a class=\'navbar-brand\' href=\'#\'>");
document.writeln("                <img src=\'https://cdnjson.com/images/2023/10/28/212239qsGyuK1o4RRFyM4E.png\' alt=\'Logo\' width=\'30\' height=\'40\' class=\'d-inline-block align-text-top\'> 猪圈");
document.writeln("            </a>");
document.writeln("            <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarNav\' aria-controls=\'navbarNav\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("                <span class=\'navbar-toggler-icon\'></span> </button>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbarNav\'>");
document.writeln("                <ul class=\'navbar-nav\'>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link active\' aria-current=\'page\' href=\'/\'>首页</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/下载.html\'>下载</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/留言.html\'>留言</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/blog.html\'>文章</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/表情包\'>表情包</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/小玩意导航页.html\'>小工具&amp;小游戏</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'/关于\'>关于</a></li>");
document.writeln("                    <form>");
document.writeln("                        <input class=\'form-control\' type=\'text\' id=\'searchInput\' placeholder=\'搜索\'>");
document.writeln("                    </form>");
document.writeln("                    <!-- 搜索结果 -->");
document.writeln("                    <br>");
document.writeln("                    <ul class=\'searchResults rounded shadow\'>");
document.writeln("                        <!-- 搜索结果将会动态加载到这里 -->");
document.writeln("                    </ul>");
document.writeln("                    <!-- JavaScript 代码 -->");
document.writeln("                    <script src=\'/js/search.js\'></script>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("    <!-- 回到顶部 -->");
document.writeln("    <div class=\'fixed-bottom\'>");
document.writeln("        <a href=\'#\' class=\'btn btn-primary bth-sm m-2\'>");
document.writeln("            <i class=\'bi bi-arrow-bar-up\'></i>");
document.writeln("        </a>");
document.writeln("    </div>");